### ISSUE TITLE
Scrolling quickly over popovers prevents removal from DOM

### ISSUE THREAD

**Issue by djfariel** [alexkatz/react-tiny-popover#55] opened 2020-04-10 20:12 UTC
Hi. I have a really weird issue. It seems like everything is working as intended EXCEPT for the final removal of the element from the DOM. This happens when I trigger a number of popups at once. It's not consistent. Sometimes they'll hide just fine, sometimes they'll fade out but not be removed. Mousing over and out of a "failed" one will cause it to work as intended again. No errors appear in the console. Here's the code and images pertaining to the state of the elements.

```
    constructor(props){
        super(props);
        this.disableTooltip = this.disableTooltip.bind(this);
        this.enableTooltip = this.enableTooltip.bind(this);
        this.state = {tooltipEnabled: false, changed: false};
    }
    disableTooltip(){
            this.setState({
                tooltipEnabled: false,
                changed: true
            });
    }

    enableTooltip() {
            this.setState({
                tooltipEnabled: true,
                changed: true
            });
    }

	render() {
		return (
            <Popover isOpen={this.state.tooltipEnabled}
              transitionDuration={0.25}
              position={'top'}
              content={({ position, targetRect, popoverRect }) => (
                <ArrowContainer
                  position={position}
                  targetRect={targetRect}
                  popoverRect={popoverRect}
                  arrowColor={"white"}
                  arrowSize={8}
                  arrowStyle={{ opacity: 1 }}>
                        <div class="item-tooltip">
                              asdf
                        </div>
                </ArrowContainer>
            )}>
                <div onMouseOver={this.enableTooltip} onMouseOut={this.disableTooltip} style={{zindex: '10000', position:'absolute', top: '0', left: '0', width:'100%', height:'100%'}}></div>
            </Popover>
		);
    }
```

![image](https://user-images.githubusercontent.com/19885486/79019908-607d3680-7b45-11ea-8dd3-a62cda415001.png)

![image](https://user-images.githubusercontent.com/19885486/79019928-712dac80-7b45-11ea-8872-062a2afbf10b.png)

As you can see on the popover, internalisOpen is false, yet isTransitioningToClosed is true, and the component is perpetually in the DOM (though transparent) until I mouse over and mouse off of it.

![image](https://user-images.githubusercontent.com/19885486/79020003-aafeb300-7b45-11ea-9577-dcc88d08d0d8.png)

Am I doing something wrong here or is this a bug?

**Comment by djfariel** [comment] 2020-04-10 21:47
Created a PR with a potential fix for this. Would appreciate if someone can tell me if this is the wrong approach to a solution. It feels hacky, but it works.
https://github.com/alexkatz/react-tiny-popover/pull/56

**Comment by Louie-Healthsite** [comment] 2020-05-21 01:51
@djfariel 
I have possibly the same issue; moving the mouse over the popover content (away from target) does hide it, but it remains invisibly in the DOM i.e. not able to click components behind it

**Comment by purplesquirrels** [comment] 2020-05-21 05:14
Same issue for me too - invisible popovers are getting stuck on screen that can still be interacted with and block the content behind. I can't reproduce it consistently so I haven't been able to narrow down the circumstances when it is occurring. Seems like it may have something to do with the page scrolling while the popover is hiding? Mousing over and out doesn't hide it for me.

**Comment by jmbastidas** [comment] 2020-07-28 00:59
Transition duration is the culprit, check: https://github.com/alexkatz/react-tiny-popover/issues/61

`
        if (!this.willUnmount || transitionDuration  > 0) {
            this.removePopoverTimeout = window.setTimeout(remove, (transitionDuration || Constants.FADE_TRANSITION) * 1000);
        } else {
            remove();
        }
`

As you can see remove is called after transitionDuration, sometimes callback is not called, some weird behavior is making setTimeout not calling the callback, there are libraries to replace setTimeout for something else which makes it to be always executed, the problem could be a combination of calling setState and few more things, but the final issue is that setTimeout is not reliable for some reason.
I don't really care about using transitionDuration, so zero is a value that will fix all problems if it can be supported.

Issue 61 has been sitting there for a some time, so we may need to live with our forks.

**Comment by alexkatz** [comment] 2020-12-08 23:18
This should be fixed in version 6, which is a fairly substantial overhaul to the `Popover` component, now fully functional and hooks-based. Give it a look when you get the chance! I'll close this for now, but will reopen if the issue somehow reappears.

**Closed by alexkatz** 2020-12-08 23:18 UTC
