### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by Valerika** [alexkatz/react-tiny-popover#100] opened 2021-01-15 12:56 UTC
Hi! 
I'm getting sometimes this error in console
```Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null```

How can I fix this?

![image](https://user-images.githubusercontent.com/15037937/104729685-77d6f900-5741-11eb-8fa7-3bf80d3c7496.png)

**Comment by ttamminen** [comment] 2021-02-10 08:13
I get this after resizing the window and opening the popover after the resize

**Comment by ttamminen** [comment] 2021-02-10 08:27
The problem started when I migrated from v4 to v6. I had a custom component (styles <button>) that opened the popover. 

I got rid of the error by doing the `React.forwardRef` thing from the documentation.

**Comment by Linktheoriginal** [comment] 2021-02-10 14:17
I'm using the React.forwardRef behavior, but I see this error on a re-render after closing a related modal.  I see elsewhere in the code where there is a ?. check for the ref, is that needed here?

**Comment by humphrey** [comment] 2021-05-06 04:53
I also receive this error.

It occurs when I resize the screen AND resizing the screen causes the component to be destroyed... For example if I have something like this (not tested), then resizing the screen past 768px breakpoint will cause this issue.  Hopefully the above fix resolves this.

```tsx
import React from 'react';
import { useMedia } from 'react-media';
import { Popover } from 'react-tiny-popover';

const MyComponent = () => {
  const media = useMedia({queries: {md: '(min-width: 768px)'});
  return (
    <>
      {media.md ? 
        <div>
            Large screen
            <Popover/>
        </div>
      :
        <div>
            Small screen
            <Popover/>
        </div>
    </>
  );
}
```

**Comment by tboerc** [comment] 2021-07-01 22:21
I can confirm that @humphrey issue is correct. On my current project, even with the `forwardRef` solution, if the resize causes the Popover to unmount, it will throw `getBoundingClientRect` error.

**Comment by RusovVladimir** [comment] 2021-08-23 14:35
I have the same issue.

**Comment by humphrey** [comment] 2021-08-23 23:16
I originally fixed with patch-package, but the issue is fixed for me
in 6.0.10

**Comment by alexkatz** [comment] 2022-06-26 19:33
Closing this issue, as it's been fixed!

**Closed by alexkatz** 2022-06-26 19:33 UTC
