### ISSUE TITLE
onOutsideClick auto fire

### ISSUE THREAD

**Issue by hmz22** [alexkatz/react-tiny-popover#45] opened 2019-09-29 19:28 UTC
Hi. 
Thx for your package but this package have little issue when content have button or other element onClick and into function use setState auto fire onOutsideClick and close popover. 
Pls fix it.

**Comment by ioulian** [comment] 2019-10-07 08:36
I have the same issue.

Using e.preventDefault() will block the onOutsideClick, it's a workaround, but it creates another problem if you need the default behaviour. Will update if I've found a solution

**Comment by jmbastidas** [comment] 2019-12-13 05:35
The problem is happening for me too, a little information that may be useful to fix this:

1. I use the popover to render a set of options/links
2. When I click one of them I show for example a react modal to confirm the action
3. I use `e.preventDefault();` to avoid adding hash to the URL, toggle the popover passing `isOpen=false` and then I set the state to show the modal:
4. All that combination breaks my app as popover HTML is not removed from the DOM
5. Removing `e.preventDefault();` from my code fixes the problem
6. So I need `e.preventDefault();` in place and the fragment of code that breaks this is located on `removePopover` function:

```
        if (!this.willUnmount) {
            this.removePopoverTimeout = window.setTimeout(remove, (transitionDuration || Constants.FADE_TRANSITION) * 1000);
        } else {
            remove();
        }
```

Compoent is will not be unmounted and popover will schedule `remove` call to remove popover from the DOM, the problem is that `e.preventDefault();` seems to interfere here and `remove` function is never called.
This setTimeout allow the popover content to fadeout before it is removed from the DOM by using `isTransitioningToClosed`, on previous version `isTransitioningToClosed` was not there and it was removed from the DOM anyway.

I tried replacing setTimeout by another implementation like rafTimeout (https://codereview.stackexchange.com/questions/47889/alternative-to-setinterval-and-settimeout) and fixed the problem, new setTimeout function was not cancelled. Another option may be this one that uses promises: https://www.npmjs.com/package/await-timeout

Also another problem is that if we want transitionDuration to be zero it takes Constants.FADE_TRANSITION by default so instead the code should handle zero properly and remove it at once.

**Comment by InkyQuill** [comment] 2020-08-04 13:09
I had a problem when onClick on the element inside the that was deleted / redrawn inside the popover would fire onOutsideClick because the trigger element was already removed from DOM when onOutsideClick checks its location. I used `e.stopPropagation();` in the onClick and that surely fixed the problem of onOutsideClick firing away.

**Comment by alexkatz** [comment] 2022-06-26 16:45
Closing for now, but please reopen if you're having trouble with the latest version.

**Closed by alexkatz** 2022-06-26 16:45 UTC

**Comment by addlistener** [comment] 2025-07-14 01:56
> I had a problem when onClick on the element inside the that was deleted / redrawn inside the popover would fire onOutsideClick because the trigger element was already removed from DOM when onOutsideClick checks its location. I used `e.stopPropagation();` in the onClick and that surely fixed the problem of onOutsideClick firing away.

I met the exact same thing.

I did not memoize a react component passed in from props. So a new button element is mounted every time. 

```
  /*
  This should be memoized!!!
  Otherwise, detecting onClickOutside will be buggy

  The bug if u don't do this ==>
    body.addEventListener('click', handleOnClickOutside, clickOutsideCapture);
      https://github.com/alexkatz/react-tiny-popover/blob/fecaaef1fbd61bbe0dd0b22be38635c57af6ceed/src/Popover.tsx#L197-L198

    !childRef.current?.contains(e.target as Node) === FALSE!!!
      https://github.com/alexkatz/react-tiny-popover/blob/fecaaef1fbd61bbe0dd0b22be38635c57af6ceed/src/Popover.tsx#L180

    The reason is e.target is already unmounted when TriggerButton is re-rendered every render.
  */
  const TriggerButtonMemo = useMemo(() => props.TriggerButton, []);
```
