### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Abdubek** [alexkatz/react-tiny-popover#53] opened 2020-03-30 09:16 UTC
I have a warning: findDOMNode was passed an instance of Popover which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

How critical is this?

**Comment by HeikkiMoilanen** [comment] 2020-04-21 09:46
Hello!

I am also getting this warning from using react-tiny-popover in strict mode:

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Popover which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

Even if it's just a deprecation warning, it's cluttering the javascript console and makes actually meaningful warnings harder to spot. Would be awesome if it could be fixed :).

**Comment by mika-kaki** [comment] 2020-04-21 11:48
I am also looking forward for a fix for this. Thanks for your great work!

**Comment by neoncube2** [comment] 2020-04-25 05:16
This looks like a duplicate of https://github.com/alexkatz/react-tiny-popover/issues/50

**Comment by alexkatz** [comment] 2020-05-05 04:52
findDOMNode has been removed in version 4.1!

**Closed by alexkatz** 2020-05-05 04:52 UTC

**Comment by mika-kaki** [comment] 2020-05-05 05:49
Awesome, thanks!
